---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ziti.dariuszski.dev
  resources:
  - ziticontrollers
  - zitirouters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ziti.dariuszski.dev
  resources:
  - ziticontrollers/finalizers
  - zitirouters/finalizers
  verbs:
  - update
- apiGroups:
  - ziti.dariuszski.dev
  resources:
  - ziticontrollers/status
  - zitirouters/status
  verbs:
  - get
  - patch
  - update
