apiVersion: ziti.dariuszski.dev/v1alpha1
kind: ZitiRouter
metadata:
  labels:
    app.kubernetes.io/name: ziti-operator
    app.kubernetes.io/managed-by: kustomize
  name: zitirouter-sample
  namespace: ziti
spec:
  zitiMgmtApi: 142e26b2-8950-4d5c-b321-04bd79e76d37.production.netfoundry.io:443
  zitiRouterEnrollmentToken: eyJhbGciOiJSUzI1NiIsImtpZCI6IjU0ZDVkMzdhZTIyYjQxZmUxYTkyMzc2ZTBhNjc4MGIxN2NjMTQxZTYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovLzE0MmUyNmIyLTg5NTAtNGQ1Yy1iMzIxLTA0YmQ3OWU3NmQzNy5wcm9kdWN0aW9uLm5ldGZvdW5kcnkuaW86NDQzIiwic3ViIjoidWoteDhuNkItIiwiYXVkIjpbIiJdLCJleHAiOjE3MzA2NTQ0MTAsImp0aSI6IjA4NDQyMmU4LTQwNmQtNGY2NC05MjJmLTQ3YjAwYjE4MWExZiIsImVtIjoiZXJvdHQiLCJjdHJscyI6bnVsbH0.uNJNQdgb4sUzaXxqD6JyQDtlBYnQjPmcHq7nv1rku6F6SVt6G_4z4H2pLjwNsJ3hoZVxh3Nn9D4-fYxU7CdWl2PHPZ6a0zRcmVGE5rFnlQMEFnYtd26dXuR_Pz74Fn5ciqquJbHXgTu3Wd9SZhJUj9z_deHSOdskboIsVk28vxwUAEzsG7ynPOzcoJ2YVdStSGj91JlWyPqplPVvf0vMCX90y2JD_E7DWvpXZt_U4yvGtn8YiC4qbMDwYSGsQVEpe-wlmlalnQIKHl_bqos2Cngh02I1RU6JTWbJyWk3Sxo4BcgiMDxUsWSJUaD07LM15GlRSFIk-oNEWgFrXC0AT_xVwBkQLCORJTT4_XVmsO2-oBXYOUTYy6pFuEQfuNdPSyYJodsvTuDULmfCpAo8kVDk3KVxpnRQN--fFjxCnUngV6xcdxxI6ZkFiDrzjTyZK2XVqMK62f2A2jwyHyrYr3xuRxrV1hxX_gqAn4qcfA0YOmIeyWzgoNu1s2csHf2CeebQk3x-gtGIfybVybQaJuWy1Tp7HWv0P3iWjbMqNawIAw42KXbU4ZR7HpByrbmXRLf6etF6pw-XExLrogjkf9cDv7qmO1OzC9rfFTSqXy_bYEtonEq0a0YYWnOBqkUguaYCTMDY-l0ncBCkPapBW2qsfEXSbqH3iczstjCZ67Y
  routerDeploymentNamePrefix: ziti-router
  debug: "1"
